version: "3"
services:
  chess-demo:
    build: webrtc-chess
    ports:
      - "8084:8080"
  yjs-websocker-server:
    build: y-websocket
    environment:
      HOST: "0.0.0.0"
    ports:
      - "1234:1234"

