version: "3"
services:
  chess-demo:
    build: webrtc-chess
    ports:
      - "8084:8080"
  thebutton:
    build: thebutton
    ports:
      - "8087:8080"
  yjs-websocket-server:
    build: y-websocket
    environment:
      HOST: "0.0.0.0"
    ports:
      - "1234:1234"
  yjs-atlaskit-demo:
    build: yjs_atlaskit
    ports:
      - "8083:80"
    depends_on:
      - yjs-websocket-server
  dashboard:
    build: dashboard
    ports:
      - "8082:80"
  caddy:
    build: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
    networks:
      - default
      - roe

volumes:
  caddy_data:
    external: true
networks:
  roe:
    external: true